#first seen here: http://www.snip2code.com/Snippet/63701/Ansible-task-to-install-nvm-and-node
# Here is how to install nvm and node in an Ansible task.
# I tried a bunch of different things, and as usual it's simple, but you have to get it right.
# The important part is that you have to shell with /bin/bash -c and source nvm.sh
---
- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install v4 && nvm alias default v4"
    creates=/home/{{ ansible_user_id }}/.nvm/alias

- name: Install litecore
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install v4 && npm install litecore"
