- name: Create deployment directory
  become: yes
  file: path={{deploy_directory}} state=directory owner=ubuntu group=ubuntu

- name: Make .litecoin conf directories
  file: path=/home/ubuntu/{{item}} state=directory owner=ubuntu group=ubuntu
  with_items:
    - .litecoin

- name: Remove useless packages from the cache
  become: yes
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Add letsencrypt repo
  become: yes
  apt_repository:
    repo: ppa:certbot/certbot
    state: present
  tags: package

- name: Add ansible repository
  become: yes
  apt_repository:
    repo: ppa:ansible/ansible
    state: present

- name: Add bitcoin repository
  become: yes
  apt_repository:
    repo: ppa:bitcoin/bitcoin
    state: present

- name: Update cache
  become: yes
  apt:
    update_cache: yes

- name: Install let's encrypt
  become: yes
  apt:
    name: python-certbot-nginx
  tags: package

- name: Install bitcoin libdb
  become: yes
  apt:
    name: libdb4.8-dev
  tags: package

- name: Install bitcoin libdb
  become: yes
  apt:
    name: libdb4.8++-dev
  tags: package


- name: Install app dependencies
  become: yes
  action: apt pkg={{item}} state=installed
  with_items:
    - git
    - build-essential
    - libtool
    - autotools-dev
    - automake
    - libssl-dev
    - libevent-dev
    - bsdmainutils
    - libboost-all-dev
    - python-dev
    - python-pip
    - libdb4.8-dev
    - libdb4.8++-dev
    - libzmq3-dev
  tags: package

- name: Install global python requirements
  pip: name={{item}} state=present
  with_items:
    - dpkt
    - gevent
    - ipaddress
    - pygeoip
    - PySocks
    - redis
    - requests


- name: Set authorized keys for ryan
  authorized_key:
    user: ubuntu
    state: present
    key: https://github.com/rromanchuk.keys

- name: "Download latest bitnodes"
  git:
    repo: 'https://github.com/rromanchuk/bitnodes.git'
    dest: /home/ubuntu/bitnodes
    clone: yes
    force: yes


- name: Add litecoin.conf to .litecoin
  template: src=litecoin.conf.j2 dest=/home/ubuntu/.litecoin/litecoin.conf force=yes

- name: Add litecore-node.json to .litecoin
  template: src=litecore-node.json.j2 dest=/home/ubuntu/.litecoin/litecore-node.json force=yes

- name: "Add special litecored bash script"
  copy:
    src: start_litecore.sh
    dest: /home/ubuntu/start_litecore.sh
    owner: ubuntu
    group: ubuntu
    mode: 0775

- name: Add crawl.service to systemd
  become: yes
  template: src=crawl.service.j2 dest=/etc/systemd/system/crawl.service force=yes

- name: Add crawl_slave.service to systemd
  become: yes
  template: src=crawl_slave.service.j2 dest=/etc/systemd/system/crawl_slave.service force=yes

- name: Add crawl_slave2.service to systemd
  become: yes
  template: src=crawl_slave2.service.j2 dest=/etc/systemd/system/crawl_slave2.service force=yes

- name: Add export.service to systemd
  become: yes
  template: src=export.service.j2 dest=/etc/systemd/system/export.service force=yes

- name: Add pcap.service to systemd
  become: yes
  template: src=pcap.service.j2 dest=/etc/systemd/system/pcap.service force=yes

- name: Add ping.service to systemd
  become: yes
  template: src=ping.service.j2 dest=/etc/systemd/system/ping.service force=yes

- name: Add ping_slave.service to systemd
  become: yes
  template: src=ping_slave.service.j2 dest=/etc/systemd/system/ping_slave.service force=yes

- name: Add ping_slave2.service to systemd
  become: yes
  template: src=ping_slave2.service.j2 dest=/etc/systemd/system/ping_slave2.service force=yes

- name: Add resolve.service to systemd
  become: yes
  template: src=resolve.service.j2 dest=/etc/systemd/system/resolve.service force=yes

- name: Add seeder.service to systemd
  become: yes
  template: src=seeder.service.j2 dest=/etc/systemd/system/seeder.service force=yes

- name: Add tcpdump.service to systemd
  become: yes
  template: src=tcpdump.service.j2 dest=/etc/systemd/system/tcpdump.service force=yes


- name: Enable and start crawl service
  become: yes
  service:
    name: crawl
    state: started
    enabled: yes

- name: Enable and start crawl_slave service
  become: yes
  service:
    name: crawl_slave
    state: started
    enabled: yes

- name: Enable and start crawl_slave service
  become: yes
  service:
    name: crawl_slave
    state: started
    enabled: yes

- name: Enable and start ping service
  become: yes
  service:
    name: ping
    state: started
    enabled: yes

- name: Enable and start ping_slave service
  become: yes
  service:
    name: ping_slave
    state: started
    enabled: yes

- name: Enable and start ping_slave2 service
  become: yes
  service:
    name: ping_slave2
    state: started
    enabled: yes

- name: Enable and start pcap service
  become: yes
  service:
    name: pcap
    state: started
    enabled: yes

- name: Enable and start export service
  become: yes
  service:
    name: export
    state: started
    enabled: yes

- name: Enable and start resolve service
  become: yes
  service:
    name: resolve
    state: started
    enabled: yes

- name: Enable and start seeder service
  become: yes
  service:
    name: seeder
    state: started
    enabled: yes

- name: Enable and start tcpdump service
  become: yes
  service:
    name: tcpdump
    state: started
    enabled: yes