- name: Install nginx
  become: yes
  apt: pkg=nginx

- name: Remove the default app
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Remove the app's config, if exists
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent



# litenodes.net

- name: Remove the getspar.com app's symlink, if exists
  become: yes
  file: path=/etc/nginx/sites-enabled/litenodes.net state=absent

- name: Configure nginx for the litenodes.net
  become: yes
  template: src=litenodes.net.j2 dest=/etc/nginx/sites-available/litenodes.net group=www-data owner=www-data force=yes

- name: Enable litenodes.net
  become: yes
  file: src=/etc/nginx/sites-available/litenodes.net dest=/etc/nginx/sites-enabled/litenodes.net state=link


# GETSPAR.COM
- name: Remove the insight.litenodes.net app's symlink, if exists
  become: yes
  file: path=/etc/nginx/sites-enabled/insight.litenodes.net state=absent

- name: Configure nginx for the insight.litenodes.net
  become: yes
  template: src=insight.litenodes.net.j2 dest=/etc/nginx/sites-available/insight.litenodes.net group=www-data owner=www-data force=yes

- name: Enable insight.litenodes.net
  become: yes
  file: src=/etc/nginx/sites-available/insight.litenodes.net dest=/etc/nginx/sites-enabled/insight.litenodes.net state=link


- name: Remove the default app's symlink, if exists
  become: yes
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Configure nginx for the insight.litenodes.net
  become: yes
  template: src=default.j2 dest=/etc/nginx/sites-available/default group=www-data owner=www-data force=yes

- name: Restart nginx
  become: yes
  action: service name=nginx state=restarted


